### ISSUE TITLE
items left does not update

### ISSUE THREAD

**Issue by foxdonut** [sveltejs/svelte-todomvc#13]
Checking and unchecking items does not update the number of items left.

**Comment by ztoben** [comment]
This should be fixed when #11 is merged.

**Comment by al6x** [comment]
Up. Also noticed this bug, seems like it has been not fixed for a while...

**Comment by Rich-Harris** [comment]
Fixed in current version
